const ACCOUNT_OR_PASSWORD_IS_NECESSARY = "账户或密码不能为空";
const ACCOUT_IS_EXIST = "账号已经存在";
const ACCOUNT_OR_PASSWORD_MISTAKE = "账户或密码错误";
const UNAUTHORIZATION = "未授权";

module.exports = {
  ACCOUNT_OR_PASSWORD_IS_NECESSARY,
  ACCOUT_IS_EXIST,
  ACCOUNT_OR_PASSWORD_MISTAKE,
  UNAUTHORIZATION,
};
