const ADDNUM = "ADDNUM";
const SUBNUM = "SUBNUM";
const MULTINUM = "MULTINUM";
const DIVNUM = "DIVNUM";
const CHANGE_BANNERS = "CHANGE_BANNERS";

export { ADDNUM, SUBNUM, MULTINUM, DIVNUM, CHANGE_BANNERS };
